(define (problem strips-logistic2)
   (:domain logistic-strips)
   (:objects tampines bedok changi package1 truck1)
   (:init (location tampines)
          (location bedok)
          (location changi)
          (package package1)
          (truck truck1)
          (truck-at-loc tampines)
          (free truck1)
          (package-at-loc package1 bedok))
   (:goal (and (package-at-loc package1 changi))))
