(define (problem strips-logistic3)
   (:domain logistic-strips)
   (:objects tampines bedok changi package1 package2 truck1)
   (:init (location tampines)
		(location bedok)
		(location changi)
		(package package1)
		(package package2)
		(truck truck1)
		(truck-at-loc tampines)
		(free truck1)
		(package-at-loc package1 bedok)
		(package-at-loc package2 changi))
   (:goal (and (package-at-loc package1 changi) 
   		(package-at-loc package2 bedok))))
